import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/providers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <ThemeProvider>
          <div className="wcontainer">
            <div className="wrapper sm:w-full md:w-5/6 mx-auto p-3">
            {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
